version: "3"

services:
  recipe-service:
    container_name: recipe-service
    build: home-made-recipe-api/.
    ports:
      - 8000:8000 # App access Port, inside container it is 8000 and mappped with 8081
    environment:
      JAR : home-made-recipe-api-1.0.0-SNAPSHOT.jar
  uiapp:
    build: home-made-recipe-ui/.
    container_name: ui-app
    depends_on:
      - recipe-service
    ports:
      - 9000:9000
