spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /api
  port: 8000

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /complaint-app-api-docs
    groups:
      enabled: true
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    path: /swagger
    csrf:
      enabled: true
